databases:
  - name: farmer-pocket-db
    plan: free

services:
  - type: web
    name: farmer-pocket
    env: docker
    repo: https://github.com/MarvinNesh/Farmer-Pocket
    plan: free
    healthCheck:
      path: /
      initialDelaySeconds: 120
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: farmer-pocket-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: GEMINI_API_KEY
        sync: false
    preDeployCommand: "flask db upgrade"